"""Makes THIRD-PARTY-NOTICES.txt: the licences of everything built into FluentSwitcher.exe or shipped with it.

FluentSwitcher itself is GPL-3.0 (LICENSE). The parts of others keep their own licences, and most of them ask
for their notice to go with the program: the file goes into the installer and the zip next to the exe, and
the settings window opens it ("About" - "Licences").

    python tools/make_notices.py <wxWidgets source tree: the one built into the program>
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD-PARTY-NOTICES.txt"

NLOHMANN_MIT = """MIT License

Copyright (c) 2013-2025 Niels Lohmann

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""

BSL = """Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE."""


def stb_licence():
    text = (ROOT / "extern" / "stb_image.h").read_text(encoding="utf-8", errors="replace")
    start = text.index("ALTERNATIVE A - MIT License")
    end = text.index("*/", start)
    return "This software is available under 2 licenses -- choose whichever you prefer.\n" + text[start:end].strip()


def main():
    wx = Path(sys.argv[1])
    parts = [
        ("SimpleSwitcher", "Aegel5, https://github.com/Aegel5/SimpleSwitcher",
         "FluentSwitcher is a modified version of SimpleSwitcher. Both are licensed under the GNU General Public\n"
         "License, version 3: see LICENSE next to this file."),
        ("LangBar++ (LangBarXX)", "Krot66, https://github.com/Krot66/LangBarXX - ideas and rules, rewritten",
         "No code of LangBar++ (an AutoHotkey script) is included. Two of its ideas are rewritten in C++: converting\n"
         "selected text as a whole, by the layout of the whole line, and the rule of the automatic layout switch - a\n"
         "word that is not a word of its language while the same keys in the other layout are one (and in the middle\n"
         "of a word: not the beginning of a word while there it is), with its exceptions (single letters, words with digits, abbreviations, a word after the layout was switched by hand,\n"
         "after a mouse click or after Backspace). LangBar++ is licensed under the GNU Lesser General Public License,\n"
         "version 3, which allows its use in FluentSwitcher under the GNU General Public License, version 3."),
        ("FrequencyWords", "Hermit Dave, https://github.com/hermitdave/FrequencyWords - word lists, CC BY-SA 4.0",
         "The lists of words built into FluentSwitcher.exe (the beginnings of words for the automatic layout switch in\n"
         "the middle of a word; source: src/data/words_ru.txt, words_en.txt) are adapted from the 2018 Russian and\n"
         "English frequency lists of FrequencyWords, made from OpenSubtitles 2018 (http://opus.nlpl.eu/OpenSubtitles2018.php):\n"
         "lower case, \"ё\" as \"е\", words of three letters and more met at least three times and known to the Windows\n"
         "dictionary of the language (tools/corpus/make_wordlist.cmd in the project). The lists are licensed under the\n"
         "Creative Commons Attribution-ShareAlike 4.0 International License\n"
         "(https://creativecommons.org/licenses/by-sa/4.0/), and so are the adapted ones. CC BY-SA 4.0 is one-way\n"
         "compatible with the GNU General Public License, version 3."),
        ("wxWidgets 3.3", "https://www.wxwidgets.org - the settings window", (wx / "docs" / "licence.txt").read_text(encoding="utf-8", errors="replace")),
        ("zlib (in wxWidgets)", "https://zlib.net", (wx / "src" / "zlib" / "LICENSE").read_text(encoding="utf-8", errors="replace")),
        ("libpng (in wxWidgets)", "http://www.libpng.org", (wx / "src" / "png" / "LICENSE").read_text(encoding="utf-8", errors="replace")),
        ("PCRE2 (in wxWidgets)", "https://github.com/PCRE2Project/pcre2", (wx / "3rdparty" / "pcre" / "LICENCE.md").read_text(encoding="utf-8", errors="replace")),
        ("NanoSVG (in wxWidgets)", "https://github.com/memononen/nanosvg", (wx / "3rdparty" / "nanosvg" / "LICENSE.txt").read_text(encoding="utf-8", errors="replace")),
        ("FluentClipper UI kit", "Dmitry Novikov - the look of the settings window",
         (ROOT / "settings" / "fluentui" / "LICENSE").read_text(encoding="utf-8")),
        ("Fluent UI System Icons", "Microsoft, https://github.com/microsoft/fluentui-system-icons - the icons",
         (ROOT / "settings" / "fluentui" / "LICENSE-FluentUI-System-Icons.txt").read_text(encoding="utf-8")),
        ("GoSquared flag icons", "https://github.com/gosquared/flags - the flags (flags\\Glossy)",
         (ROOT / "bin_files" / "flags" / "Glossy" / "LICENSE-GoSquared.txt").read_text(encoding="utf-8")),
        ("JSON for Modern C++", "Niels Lohmann, https://github.com/nlohmann/json", NLOHMANN_MIT),
        ("stb_image", "Sean Barrett, https://github.com/nothings/stb", stb_licence()),
        ("simple_enum", "Artur Bać, https://github.com/arturbac/simple_enum", BSL),
    ]
    lines = ["FluentSwitcher - third-party notices", "=" * 36, "",
             "FluentSwitcher includes the following parts of others. Each keeps its own licence.", ""]
    for name, where, _ in parts:
        lines.append(f"  - {name} ({where.split(' - ')[0]})")
    for name, where, text in parts:
        lines += ["", "", "-" * 78, f"{name}", f"{where}", "-" * 78, "", text.replace("\r\n", "\n").strip()]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\r\n")
    print(f"{len(parts)} parts -> {OUT}")


if __name__ == "__main__":
    main()
